services:
  backend:
    develop:
      watch:
        - action: sync
          path: backend
          target: /app
        - action: rebuild
          path: backend/requirements.txt
        - action: rebuild
          path: backend/Dockerfile
  frontend:
    develop:
      watch:
        - action: sync
          path: frontend
          target: /app
        - action: rebuild
          path: frontend/package.json
        - action: rebuild
          path: frontend/package-lock.json
        - action: rebuild
          path: frontend/Dockerfile
